### ISSUE TITLE
AttributeError: 'SharedJobCluster' object has no attribute 'job_result_port'

### ISSUE THREAD

**Issue by jzuiddam** [pgiri/dispy#25]
Dear Giridhar,

I am getting the following exception when using SharedJobCluster with dispy 4.6.2.

```
2015-12-30 12:43:25,456 - dispy - Storing fault recovery information in "_dispy_20151230124325"
2015-12-30 12:43:35,593 - asyncoro - uncaught exception in timer_task/30201288:
Traceback (most recent call last):
  File "/ufs/jzuiddam/pypy4env/site-packages/asyncoro/__init__.py", line 3226, in _schedule
    retval = coro._generator.send(coro._value)
  File "/ufs/jzuiddam/pypy4env/site-packages/dispy/__init__.py", line 971, in timer_task
    (cluster.scheduler_ip_addr, cluster.job_result_port))
AttributeError: 'SharedJobCluster' object has no attribute 'job_result_port'

2015-12-30 12:46:20,420 - asyncoro - invalid coroutine 30201288 to resume
2015-12-30 12:49:15,627 - asyncoro - invalid coroutine 30201288 to resume
2015-12-30 12:52:07,983 - asyncoro - invalid coroutine 30201288 to resume
```

Am I doing something wrong? 

Best, Jeroen

**Comment by jzuiddam** [comment]
The dispyscheduler gives me the following exception, which is possibly related to the above.

```
2015-12-30 14:45:21,233 - asyncoro - uncaught exception in timer_task/140708161349296:
Traceback (most recent call last):
  File "/ufs/jzuiddam/pypy4env/site-packages/asyncoro/__init__.py", line 3226, in _schedule
    retval = coro._generator.send(coro._value)
  File "/ufs/jzuiddam/pypy4env/bin/dispyscheduler.py", line 947, in timer_task
    if node.busy and (node.last_pulse + (5 * self.pulse_interval)) < now:
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
```

**Comment by pgiri** [comment]
Can you try latest release 4.6.3?  Can you also post sample program that causes this issue? I haven't seen this error before even with 4.6.2 so it would help.

Thanks,
Giri

**Comment by pgiri** [comment]
I am guessing that following may fix the issue you mention:

[pulse.txt](https://github.com/pgiri/dispy/files/74997/pulse.txt)

**Comment by jzuiddam** [comment]
I can reproduce the problem as follows in 4.6.2. Run `dispyscheduler.py --pulse_interval 3` and `~/pypy4env/bin/dispynode.py -c 1`. Then run the following.

```python
import dispy
import time

def f(foo):
    time.sleep(10)

cluster = dispy.SharedJobCluster(f, depends=[f], reentrant=True)

for i in range(10):
    job = cluster.submit(i)

cluster.wait()
cluster.close()
```

It gives

```
2015-12-30 19:48:27,501 - asyncoro - uncaught exception in timer_task/4361762360:
Traceback (most recent call last):
  File "/Users/jzuiddam/pypy4env/site-packages/asyncoro/__init__.py", line 3226, in _schedule
    retval = coro._generator.send(coro._value)
  File "/Users/jzuiddam/pypy4env/site-packages/dispy/__init__.py", line 971, in timer_task
    (cluster.scheduler_ip_addr, cluster.job_result_port))
AttributeError: 'SharedJobCluster' object has no attribute 'job_result_port'
```

I haven't tried 4.6.3 yet.

**Comment by jzuiddam** [comment]
I get the same exception in 4.6.3.

**Comment by jzuiddam** [comment]
After having applied your patch I indeed don't see the exception anymore. The other exception however still occurs. I don't have a small example to reproduce this yet.

```
Traceback (most recent call last):
  File "/ufs/jzuiddam/pypy4env/site-packages/asyncoro/__init__.py", line 3226, in _schedule
    retval = coro._generator.send(coro._value)
  File "/ufs/jzuiddam/pypy4env/bin/dispyscheduler.py", line 947, in timer_task
    if node.busy and (node.last_pulse + (5 * self.pulse_interval)) < now:
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
```

**Comment by pgiri** [comment]
I have committed fix for both issues, although for second issue I am guessing at what might be (or have gone) wrong. Is it likely that the node is dead or not reachable after accepting computation? Is it possible that you can reproduce this issue (even if the example is not simple) to know if the fix works? If the fix works for you, I think releasing a new version soon makes sense.

**Comment by jzuiddam** [comment]
Did you commit the right file? I only see changes in `Dockerfile`.

**Comment by pgiri** [comment]
Sorry, I thought I committed both files, but apparently I missed it. It is now committed. Please let me know if this indeed fixes the problem.

**Comment by pgiri** [comment]
If you had a chance to test the above fix, can you confirm if it fixes second part of the problem (with adding None to float)?

**Comment by jasonterhune** [comment]
I am still getting this error with 4.6.3. It doesn't seem to interfere with the computations though.

    2016-01-07 10:52:28,808 - asyncoro - uncaught exception in timer_task/7347432:
    Traceback (most recent call last):
      File "C:\Python27\lib\site-packages\asyncoro\__init__.py", line 3244, in _schedule
        retval = coro._generator.send(coro._value)
      File "C:\Python27\lib\site-packages\dispy\__init__.py", line 1018, in timer_task
        (cluster.scheduler_ip_addr, cluster.job_result_port))
    AttributeError: 'SharedJobCluster' object has no attribute 'job_result_port'

**Comment by pgiri** [comment]
I meant the code as in github now, not 4.6.3 release. Latest from github should work, as I understand.

**Comment by pgiri** [comment]
This has been fixed in 4.6.4 release.
