### ISSUE TITLE
No way to clear dispynode

### ISSUE THREAD

**Issue by RexFuzzle** [pgiri/dispy#32]
So I have quite a complex class that calls a system process to do some processing using a temporary folder and returns some data. The temporary folder is created new each time the class is instantiated using a UUID so there is no way the data is carried over that way. 
The problem is that the setup works fine the first time it is run (New dispynode.py) but when running the code a second time, using the same dispynode.py it does not work.
I am looking for a way to clear the dispynode or at least see what is causing the issue- any advice?

**Comment by pgiri** [comment]
I don't quite understand the issue. dispynode creates separate directory for each computation and all files are saved under that by default. The same directory is also set as working directory so if your jobs (and 'setup' function) create / save files either at 'os.getcwd()' or without directory component, then dispynode will also cleanup after computation is done.

If you want to see what directories are being used for computations, you can enable debug log with dispynode (i.e., run with 'dispynode.py -d') which shows directories used / files transferred etc. If you can access the nodes, you can explore files there.

**Comment by RexFuzzle** [comment]
Ok, thanks, will take another look- it seems that some files are being left in the directories used by dispy node between processes, but will confirm and get back to you.

**Comment by pgiri** [comment]
I think I understand your problem better now. Your computation creates files and dispynode is not removing them when cluster is closed? If so, dispynode only removes files transferred by clients with 'depends' and 'send_file'. Files created by computation are not removed - they should be removed by computations / 'cleanup' function.

**Comment by pgiri** [comment]
I committed 56271da..3a751d2 that addresses this issue (as I understand it). You can either apply this, or just get dispynode.py from https://raw.githubusercontent.com/pgiri/dispy/master/py2/dispy/dispynode.py and test.

**Comment by RexFuzzle** [comment]
Thank you, but the fix seems to break asyncoro due to the extra argument being sent on line 381 of dispynode.py. I tried installing the latest asyncoro (Thought there may be some changes there not on pypi) but no luck either.

**Comment by pgiri** [comment]
Sorry about that; code meant for another patch were also committed. I have now committed other changes and you can get https://raw.githubusercontent.com/pgiri/dispy/master/py2/dispy/__init__.py as well and replace \_\_init\_\_.py in your dispy package.

No need to upgrade asyncoro, although no harm.

**Comment by RexFuzzle** [comment]
Thanks, that is now removing the folder at the end of the first run (Which would remain but was empty), but has not completely solved my issue. I will have to investigate further to find out what is causing it.

**Comment by RexFuzzle** [comment]
Ok, so after some more investigation I found that it was an issue when running the node and client in the same virtual environment. As soon as I put dispy node in its own virtual environment it was all sorted. Just putting this here for the sake of completeness.

**Comment by pgiri** [comment]
I still don't quite understand the issue, actually. Is it possible to give a simple client program that shows this problem? If not, can you give the statement that creates dispy.JobCluster?

**Comment by RexFuzzle** [comment]
I'll try, but I don't know if I'll be able to as it may have something to the OMPython/OpenModelica instance that each job is starting and so a minimum working example may be tricky, but will see what I can do.

**Comment by pgiri** [comment]
I don't need to know your own program; you can create a simple program with 'compute' as given in examples supplied in dispy, but transfer files / create instances etc. that show the behavior you describe.
