### ISSUE TITLE
Dropping/hanging on tasks

### ISSUE THREAD

**Issue by matthewwardrop** [pgiri/dispy#4]
Dispy 3.23 dropped tasks reproducibly, as already communicated. Dispy 4.1 greatly improves the situation, but I'm unfortunately still getting some tasks which do not complete (but which I know should, since I have an independent multiprocessing based scheduler). I'm filing this so that if anyone else experiences this, they've got somewhere to comment. I'll try to get to the bottom of this, and file a patch once the 4.1 code is synced.

**Comment by matthewwardrop** [comment]
FWIW, I had a similar problem when implementing my multiprocessing scheduler. I found that multiprocessing did not always terminate correctly. My workaround was not to trust multiprocessing, and to kill threads after the jobs had returned their values.

**Comment by pgiri** [comment]
Can you try http interface and see if it shows jobs still running and may be cancel them if you think they have finished? You can also start dispynode with debug option to get useful information.

**Comment by matthewwardrop** [comment]
I've run a few long-ish runs (~10000 jobs taking several hours each), and I've modified dispynode to print messages at certain points in the code. Terminating these jobs via the http interface then yields a DispyJob that has None for all of its attributes. Interestingly, there is no rhyme or reason the the jobs that fail (they are a different task each time), and where they start to hang seems to differ too. For example, sometimes the _dispy_job_func function hangs at some point before the try/except block ; and sometimes it hangs around the point of executing the "compute" function. I can find no obvious bug in dispy; and cannot see a way around it either. It's very disappointing, because it means I have to supervise runs, rather than allowing multiple JobClusters to queue up. It might even be better to manually queue up jobs on the remote servers. If I cannot find the bug soon, the expediency of my thesis may depend on me giving up for a time.

**Comment by pgiri** [comment]
I have been using dispy with Python 2.7 for a long time with many thousands of jobs and never encountered this. If it is possible to isolate to a test that I can use to reproduce, I can help.
If your program is not too complicated to port to Python 3, then may be you want to give that a try (in case the problem is with your Python version).
If DispyJob is None, it most likely means that the job has finished. Run both dispy and dispynode in debug mode and see the logs? Giri

**Comment by matthewwardrop** [comment]
I've run the same simulation twice, both with ~10000 runs, and both with two servers; and both times exactly two jobs failed. This could simply be a coincidence. I am going to run it once more. In one instance, the two jobs were on different hosts; on the second instance, the jobs were on the same host. The affected jobs were different between the two runs. In both cases, terminating the jobs via the http interface led to a DispyJob object being returned from dispy with its "result", "stdout", "stderr" and "exception" attributes set to `None` (DispyJob itself was not `None`). The CPU utilisation at the time of inspection was 0%. Dispynode.py (with debug information enabled) shows no interesting information about the stalled jobs, beyond that they were submitted.

In 3 of the four of the failed jobs recorded, execution never showed any evidence of being within the _dispy_job_func function. In one case, the last recorded point is just before the "compute" function would have been executed.

My program is quite complicated, but the main reason I've stuck with Python 2 is that it is noticeably faster in my test cases (I think mainly because of unicode by default, for me). It's also a bit late in my PhD to consider a port (I hope to submit my thesis in a couple of months, and dispy was going to be a quick way to increase the computational resources available to my simulations).

It is difficult to isolate a simple test case; because if I limit the number of runs, or if I decrease the computational complexity of the "compute" function (i.e. comment out some of its dependencies), everything works fine. If you'd like to test my simulation on your machine, I'm quite happy to send you the relevant code (but since I'm going to be publishing results from it shortly, I'd prefer not to do that in a public forum).

**Comment by matthewwardrop** [comment]
The same outcome occurred again for my last test. Killing dispynode.py on my two machines, and starting a new one on those machines or elsewhere allows the job to finish in a few seconds. Thanks for looking into this. Are you able to reproduce it?

**Comment by pgiri** [comment]
I have trouble getting it going. I didn't have pyximport / pyxbuild, which I downloaded and installed. Now I get following error:
ImportError: Building module failed: ["UnknownFileError: unknown file type '.pyx' (from 'dispy_test/parampy/quantities.pyx')\n"]
I am wondering if I can get rid of pyximport not least because this is not standard with Python (CPython); is this possible?
I am going to release 4.2 tonight / tomorrow, because of an issue with running programs (I use functions exclusively so didn't realize the issue until someone posted a bug report today). Anyway, I will take a look at your scripts over the weekend. Hopefully I can get it going before that.
Giri 


     On Wednesday, May 6, 2015 6:58 PM, Matthew Wardrop <notifications@github.com> wrote:
   

 The same outcome occurred again for my last test. Killing dispynode.py on my two machines, and starting a new one on those machines or elsewhere allows the job to finish in a few seconds. Thanks for looking into this. Are you able to reproduce it?—

**Comment by matthewwardrop** [comment]
Rather than downloading pyximport / pyxbuild, just run pip install cython . Cython includes and supersedes these separate modules. Pyximport as configured will then compile the python code to C at runtime if that is required (i.e. it hasn't been done already). Cython is used because I get a considerable speed boost by precompiling the python modules into C. Technically, however, I haven't taken advantage of the c-extensions; so all of the *.pyx files could be renamed to *.py and they will still work. It is possible that these phantom bugs are coming from this C conversion; but given that it works in my multiprocessing implementation, I'm not entirely convinced.

I realised this morning that dispynode.py will have to have qubricks and parampy on its path in order to function. So maybe run it from within the same folder; or pip install qubricks and parampy from my github repositories.

Let me know if the scripts are still not working, and I'll precompile the modules for you (assuming you are on 64bit linux).

**Comment by pgiri** [comment]
I git it going and started a run an hour ago. Initially it was taking long time to finish each job, but now it is going lot quicker. The estimate says 4 hrs to finish.  Will let you know if I find anything. Giri 


     On Wednesday, May 6, 2015 9:04 PM, Matthew Wardrop <notifications@github.com> wrote:
   

 Rather than downloading pyximport / pyxbuild, just run pip install cython . Cython includes and supersedes these separate modules. Pyximport as configured will then compile the python code to C at runtime if that is required (i.e. it hasn't been done already). Cython is used because I get a considerable speed boost by precompiling the python modules into C. Technically, however, I haven't taken advantage of the c-extensions; so all of the *.pyx files could be renamed to *.py and they will still work. It is possible that these phantom bugs are coming from this C conversion; but given that it works in my multiprocessing implementation, I'm not entirely convinced.I realised this morning that dispynode.py will have to have qubricks and parampy on its path in order to function. So maybe run it from within the same folder; or pip install qubricks and parampy from my github repositories.Let me know if the scripts are still not working, and I'll precompile the modules for you (assuming you are on 64bit linux).—

**Comment by matthewwardrop** [comment]
Thanks Giri :).

**Comment by pgiri** [comment]
The run finished but I got an error in generating latex report (I didn't have latex on this server).
The node's output (last few lines):
2015-05-07 02:50:11,850 - dispynode - Module "qubricks.sympy" is left behind by "integrate" at 172.16.10.252015-05-07 02:50:11,851 - dispynode - Module "Cython.re" is left behind by "integrate" at 172.16.10.252015-05-07 02:50:11,851 - dispynode - Module "matplotlib.textpath" is left behind by "integrate" at 172.16.10.252015-05-07 02:50:11,851 - dispynode - Module "sympy.mpmath.ctx_base" is left behind by "integrate" at 172.16.10.252015-05-07 02:50:11,851 - dispynode - Removing "/tmp/dispy/node/integrate_Y7_JVa"
The client:
                           Node |  CPUs |    Jobs |    Sec/Job | Node Time Sec------------------------------------------------------------------------------ 172.16.10.25               |       4 |    9900 |      5.274 |     52211.257
DONEProcessing... DONEPlotting...sh: 1: latex: not found Error
 Giri 


     On Wednesday, May 6, 2015 11:40 PM, Matthew Wardrop <notifications@github.com> wrote:
   

 Thanks Giri :).—

**Comment by matthewwardrop** [comment]
Thanks so much for checking it out. So you didn't have any jobs left
behind... very interesting. Were you running on just one server? Are you
using Python 2.7.9? In Linux?

**Comment by pgiri** [comment]
I am using
Python 2.7.8 (default, Oct 20 2014, 15:05:19)[GCC 4.9.1] on linux2
on Ubuntu 14.10, 4 core single server.
There were no jobs left hanging, as the output from server I showed you. The last message "Removing" is when computation finished (all jobs executed and client received all replies back and sent message to the node to close).
I have installed latex now on this, so I can give it another go tonight / over the weekend to see if another run might exhibit your problem. If you want me to send you any results file(s) from last night's run, let me know and I can send you. I think
 fidelity_dc,xy/butterfly_sinusoidal/Jz,9xJc,11/data.shelf

is the file that stores results, so attaching that here.

 Giri 


     On Thursday, May 7, 2015 7:38 AM, Matthew Wardrop <notifications@github.com> wrote:
   

 Thanks so much for checking it out. So you didn't have any jobs left
behind... very interesting. Were you running on just one server? Are you
using Python 2.7.9? In Linux?

**Comment by matthewwardrop** [comment]
Thanks Giri. The output of the computation is not as useful to me as the assurance that there exists some way that I can run these simulations back to back without having to supervise the runs. Killing and rerunning the dispynode.py servers allows me to finish any computation, but it means that I need to be there to do it... and I can't queue up 10 plots, for example. I'm really not sure why my machines are having trouble. I'll try again with different machines. I'll get back to you if I can better isolate the problem. Until then, it sounds like its working for you... and the problem might just be the combination of hardware/software I'm using on my machine. Again, I'm very grateful for your time and assistance.

**Comment by pgiri** [comment]
BTW, in case you are still dealing with jobs not finishing, you can automate cancelling any job that hasn't finished within certain time (since in this it doesn't matter that a few jobs don't finish normally). For example, you can keep track of jobs submitted, job callback remove finished jobs from this,  and have a timer (say, every minute) go through pending jobs, and cancel any jobs that have been submitted before some time.

While this is not ideal solution, this should work in your case, I believe.

**Comment by matthewwardrop** [comment]
I have only been able to reliably reproduce the hanging on one of my machines. The other example, whereby it hung on two machines, has not recurred. I'll leave the bug open for now, until I finish running some pretty ginormous runs. Would you be open to adding a `max_runtime` (per job) to JobCluster?

**Comment by matthewwardrop** [comment]
With the "ginormous" (with ~ 30000 - 80000 runs), I'm getting jobs hanging on all of my machines; again with no rhyme or reason. A `max_runtime` option would help here (and I'm happy to provide a pull request for the feature). I still don't know what's going on, but can only presume there's some interplay between cython and multiprocessing that is breaking something down (though it's odd I don't see the same problem in my implementation). I'll look into it, and provide a pull request if I find out what's going on. I'll leave the bug open for now, in case I need to chat about it a bit more.

**Comment by pgiri** [comment]
As I mentioned earlier, jobs can be monitored and cancelled with a timer and 'callback' function. As this is a unique problem, I don't think it is useful to include it in dispy / dispynode. If this seems to occur with just multiprocessing (without dispy), then likely cython and/or other parts are causing the issue (as you mention).

**Comment by matthewwardrop** [comment]
Actually, it only occurs with dispy; not multiprocessing, which was my point of confusion. I did read your earlier mention of a timer and a 'callback'; but when I thought about implementing it, I thought it made sense to do it in the actual task loop (in dispy). Of course, that only makes sense if it is generally useful beyond my specific use case. I would argue that it may well be useful more generally, for example to give peace of mind against runaway tasks, or in tasks that could run forever, but which you want the result after a fix amount of time. If you're not keen to implement it in dispy, I understand. In my instance, I'll probably just kill tasks manually.

**Comment by pgiri** [comment]
Can you try current git repo? If the problem is node not being able to connect to client to send the result, then current git should fix that issue.

**Comment by matthewwardrop** [comment]
I'll try it, and let you know :).

**Comment by matthewwardrop** [comment]
Unfortunately, the problems persist. And now I get _dispy_.* files spamming my folder. Is this the intended behaviour? Perhaps only dump those files if problems do occur?

**Comment by pgiri** [comment]
Current tree should not leave _dispy_ files; update to latest.

dispynode now sends any pending jobs every 10 minutes by default. If you want, you can set a lower 'pulse_interval' to check for pending jobs more frequently. If you are seeing jobs 'hanging' for more than 'pulse_interval' period, then can you check if you have any files in /tmp/dispy/node/<client_ip>/_dispy_job_reply_* files? These files are created by dispynode if it can't connect to client (for some reason). If there are no files, then either multiprocessing.Process has not finished, or some issue with multiprocessing.Queue, I guess.

**Comment by matthewwardrop** [comment]
Things seem to be working acceptably (though I haven't had much time to test everything fully). In particular, though; it seems the hanging is due to an interplay of openblas threading with multiprocessin, which is a known issue with upstream numpy. I've managed to effectively turn off the threading, which solves the problem. Good to know that dispy is not at fault, which means I can close this issue with impunity :).
