### ISSUE TITLE
Trying to unpickle leads to many exceptions

### ISSUE THREAD

**Issue by jonasc** [pgiri/dispy#48]
I'm running many jobs (around 10000) through a job scheduler instance (on the same server as the client program) and after getting the first good results I receive a lot of the following exceptions (probably because of the serialization introduced in #43).
~~~
2016-07-20 14:42:14 dispy - Received reply for job (100, 0, 9, 11) / 139670687700816 from 160.45.45.76
2016-07-20 14:42:14 asyncoro - uncaught exception in ~tcp_task/140623224265248:
Traceback (most recent call last):
  File "XXX/usr/local/lib/python3.5/site-packages/asyncoro/__init__.py", line 3752, in _schedule
    retval = coro._generator.throw(*exc)
  File "YYY/opt/dispy/py3/dispy/__init__.py", line 833, in tcp_task
    yield self.job_reply_process(info, conn, addr)
  File "XXX/usr/local/lib/python3.5/site-packages/asyncoro/__init__.py", line 3754, in _schedule
    retval = coro._generator.send(coro._value)
  File "YYY/opt/dispy/py3/dispy/__init__.py", line 1522, in job_reply_process
    job.result = unserialize(reply.result)
  File "XXX/usr/local/lib/python3.5/site-packages/asyncoro/__init__.py", line 76, in unserialize
    return pickle.loads(pkl)
TypeError: a bytes-like object is required, not 'NoneType'
~~~

After that I also receive a huge amount of those messages (scheduler runs on same machine as client):
~~~
2016-07-20 14:45:31 dispy - Ignoring invalid reply for job 139670687434696 from 127.0.0.1
~~~
Interestingly the job "number" is mostly (or maybe always, I could not check easily) the same. Can you tell me how this number is calculated anyways, because different jobs (different job ids, which are a four-tuple of integers in my case) seem to have the same job number.

**Comment by pgiri** [comment]
Can you confirm if this is with 4.6.15 release or 4.6.14 with the patches as of last week? If a job raises exception, code as of last week may cause above error, but 4.6.15 should work fine.

The id reported above is result of 'id' method on _job instance. This number may repeat if a job is finished (garbage collected), and another instance has same 'id'.

**Comment by jonasc** [comment]
I'll have a look at it. Strangely, right now I'm not able to reproduce the error. I'll try to give further information whenever this error crosses my path again.

**Comment by pgiri** [comment]
This has been addressed in 4.6.15 release.

**Comment by jonasc** [comment]
I'm reopening because this issue still seem to exist.
It is a pretty non-deterministic issue, it took me 12 runs with the following program to see it.
https://gist.github.com/jonasc/78832feac7b376d708f1bd5d40e85bcc

See the log file (also in the link above). As indicated in the start post the client computer is the same as the one running the scheduler node.

**Comment by pgiri** [comment]
The issue with above program is something else, actually. I committed fix for it  in 85fa1b7..0ab5c4e.
